[phases]
build = "npm install && npm run build"

[backend]
install = "cd backend && npm install"
build = "cd backend && npm run build"
start = "cd backend && npm start"

[frontend]
install = "cd frontend && npm install"
build = "cd frontend && npm run build"
start = "cd frontend && npm start"