[phases]

# Backend configuration
[phases.backend.install]
run = "npm install"
working_directory = "./backend"

[phases.backend.build]
run = "npm run build"
working_directory = "./backend"

[phases.backend.start]
run = "npm start"
working_directory = "./backend"

# Frontend configuration
[phases.frontend.install]
run = "npm install"
working_directory = "./frontend"

[phases.frontend.build]
run = "npm run build"
working_directory = "./frontend"

[phases.frontend.start]
run = "npm start"
working_directory = "./frontend"
